name: Tests

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'pretix_ldap_mails/locale/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'pretix_ldap_mails/locale/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: sudo apt update && sudo apt install gettext
      - name: Install LDAP dependencies
        run: sudo apt install libsasl2-dev python-dev libldap2-dev libssl-dev
      - name: Install pretix and plugin dependencies
        run: pip3 install pretix python-ldap
      - name: Install Dependencies
        run: pip3 install pytest pytest-django -Ue .
      - name: Run checks
        run: py.test tests
